CREATE SEQUENCE CLIENT_SEQUENCE START WITH 20 INCREMENT BY 1;
CREATE SEQUENCE ASSURANCE_SEQUENCE START WITH 20 INCREMENT BY 1;

CREATE TABLE COMPTE_BANCAIRE(
	iban varchar(32),
	proprietaire VARCHAR (50),
	swift_code varchar(8),
	PRIMARY KEY (iban)
);


CREATE TABLE CLIENT(
	idClient INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
	nom varchar(20),
        Siren varchar(20) NULL,
        dateNaissance DATE NULL,
	primary key (idClient)
);



CREATE TABLE COMPTE_CLIENT(
  idClient INTEGER ,
  iban varchar(20),
  ComptePrincipal boolean DEFAULT 0,
  PRIMARY KEY (idClient, iban),
	FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
  FOREIGN KEY (iban) REFERENCES COMPTE_BANCAIRE(iban)
);


create TABLE ASSURANCE(
    idAssurance INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
    Numero INTEGER not null,
    DateSouscription varchar(20) not null,
    DateAnniversaire varchar(20) not null,
    DatePrelevement varchar(20) not null,
    typeAssurance varchar(20) not null,
    PRIMARY KEY (idAssurance)
  );

create TABLE AssuranceAuto(

 idAuto INTEGER,
 Immatriculation varchar(20),
 Bonus INTEGER,
 FOREIGN KEY (idAuto) REFERENCES ASSURANCE(IdAssurance)
);

create TABLE AssuranceHabitation(

 idHabitation INTEGER,
 Adresse varchar(20),
 ValeurCouverture varchar(20),
 FOREIGN KEY (idHabitation) REFERENCES ASSURANCE(IdAssurance)
);

 create TABLE CLIENT_ASSURANCE(
    idClient INTEGER ,
    idAssurance INTEGER ,
    PRIMARY KEY (idClient, idAssurance),
    FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
    FOREIGN KEY (idAssurance) REFERENCES ASSURANCE(idAssurance)
  )

 create TABLE Echeances(
  idEcheance INTEGER,
  prix INTEGER,
  DateEmission varchar(20),
  DatePaiement varchar(20),
  DateEmissionFacture varchar(20),
  PRIMARY KEY(idEcheance)
);
